name: Build and Pack AliFsmnVad

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore and Build (Linux)
      run: |
        dotnet restore AliFsmnVad/AliFsmnVad.csproj
        dotnet build AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0
        
    - name: Pack (Linux)
      run: |
        mkdir -p nupkg
        dotnet pack AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0 -o ./nupkg

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install iOS/MacCatalyst workloads
      run: |
        dotnet workload install ios maccatalyst
        
    - name: Restore and Build (Mac)
      run: |
        dotnet restore AliFsmnVad/AliFsmnVad.csproj
        dotnet build AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0
        dotnet build AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0-ios
        dotnet build AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0-maccatalyst
        
    - name: Pack (Mac)
      run: |
        mkdir -p nupkg
        dotnet pack AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0 -o ./nupkg
        dotnet pack AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0-ios -o ./nupkg
        dotnet pack AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0-maccatalyst -o ./nupkg

  build_windows_android:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install Android workload
      run: dotnet workload install android
    - name: Build
      run: |
        # 使用 MSBuild 的 ExcludeFromBuild 属性
        dotnet build AliFsmnVad.sln -p:ExcludeFromBuild=true -p:ExcludedProjects="AliFsmnVad.Examples.csproj"
    - name: Restore and Build (Android)
      run: |
        dotnet restore AliFsmnVad/AliFsmnVad.csproj
        dotnet build AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0-android
    - name: Pack (Android)
      run: |
        mkdir -p nupkg
        dotnet pack AliFsmnVad/AliFsmnVad.csproj -c Release -f net9.0-android -o ./nupkg
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-nupkg
        path: ./nupkg/*.nupkg
    
  publish_nuget:
    needs: [build_linux, build_macos, build_windows_android]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nupkg
        path: ./nupkg
        
    - name: Publish to NuGet
      run: |
        dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    # 新增：上传打包后的文件作为 Artifacts
    - name: Upload packed files
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages  # Artifacts 名称（自定义）
        path: ./nupkg/AliFsmnVad  # 指向 pack 输出的目录（与 pack 步骤的 --output 一致）
        retention-days: 7  # 保留 7 天（可选，默认 90 天）
