name: Build, Pack and Publish to NuGet
run: dotnet build --configuration Release --no-restore
  if: |
    !(matrix.os != 'macos-latest' && 
      (contains(matrix.targetframework, 'ios') || contains(matrix.targetframework, 'maccatalyst')))
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        dotnet-version: [ '9.0.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    # 关键修复：还原移动平台所需的工作负载（Android/iOS等）
    - name: Restore .NET workloads
      run: dotnet workload restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg

    - name: Publish to NuGet
      if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
